name: ignis-automation-debugging-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: WebdriverIO_AutomationTests
      type: git
      name: ignis-automation-testing-e2e

jobs:
  - job: Install
    pool:
      vmImage: 'windows-latest'

    steps:
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - bash: |
            npm install
          displayName: Npm install

  - job: RUN
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - bash: |
            npm install
          displayName: Npm install
